apiVersion: apps/v1
kind: Deployment
metadata:
  name: bulletin
spec:
  replicas: 1
  selector:
    matchLabels:
        app: bulletin
  template:
    metadata:
      labels:
        app: bulletin
    spec:
      containers:
      - name: bulletin
        image: cloudguru.azurecr.io/bulletin:v1
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 255m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: bulletin
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: bulletin